---
- name: Install Custom Limits File
  become: yes
  template:
      src: "templates/elevated-limits.conf.j2"
      dest: "/etc/security/limits.d/90-nproc.conf"
      mode: 0555
  when: raise_os_limits

# unfortunately, these won't take witout a reboot.  Not sure how to get around that.
#- name: Test max user processes limit
#  command: "ulimit -u"
#  when: raise_os_limits

#- name: Test open files limit
#  command: "ulimit -n"
#  when: raise_os_limits
